# Generated by Django 3.1.14 on 2024-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='event',
            name='room_id',
            field=models.CharField(max_length=60),
        ),
    ]
