# Generated by Django 3.1.14 on 2024-08-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20240816_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
    ]
